# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extuser',
            name='basicinfo_ptr',
        ),
        migrations.RemoveField(
            model_name='extuser',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExtUser',
        ),
    ]
