# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emboss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emboss.Media')),
                ('client_name', models.CharField(blank=True, max_length=30)),
            ],
            bases=('emboss.media',),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emboss.Media')),
                ('venue', models.CharField(blank=True, max_length=30)),
            ],
            bases=('emboss.media',),
        ),
    ]
