# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 22:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emboss', '0003_auto_20160115_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='parent_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
