# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emboss', '0005_media_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbossData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='consumed',
            field=models.BooleanField(default=0),
        ),
    ]
