# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20160115_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FloatField()),
                ('units', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('flag', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('parent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data_stream',
            field=models.ManyToManyField(to='utils.DataStream'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='parent_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
