# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Campaign', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_xml_path', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('parent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Step', max_length=40)),
                ('next_step', models.CharField(default=-1, max_length=50)),
                ('_filter', models.CharField(blank=True, max_length=100)),
                ('exe_date', models.DateTimeField(blank=True, verbose_name='execution date')),
                ('message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='beam.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Template', max_length=50)),
                ('twilio_xml_path', models.CharField(max_length=100)),
                ('isPublic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('leadinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='beam.LeadInfo')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            bases=('beam.leadinfo',),
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_step',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='beam.Step'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parent_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
